### ISSUE TITLE
[Bug] Not support NCM V3.0.0 Beta

### ISSUE THREAD

**Issue by yangnuozhen** [MicroCBer/BetterUniverse-Installer#57]
如题
![image](https://github.com/MicroCBer/BetterUniverse-Installer/assets/56541171/a18ef1eb-7bc0-48d2-b5dd-6c20feb1a9eb)

貌似是因为[这里](https://gitee.com/microblock/better-ncm-v2-data/blob/master/betterncm/betterncm1.json)没有添加1.3.0-rc1 版本所致。

为了不影响未升级用户，也许可以试试加个3.0 安装器的分支（？

**Comment by MicroCBer** [comment]
这是故意的：
1. 1.3.0-rc1不完善 且没有几个插件支持
2. 安装器还没支持分流 现在加进去会导致老版本用户无法正常安装
